# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

## Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list) 

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [11]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0)  

array([0., 1., 2.])

In [13]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [17]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [20]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [21]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,10) 

array([], dtype=int64)

In [23]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

In [ ]:
np.arange(0,10,3)

In [ ]:
np.arange(10,30,5,8)

In [ ]:
np.zeros(3) # parameter  tunning 

In [ ]:
np.zeros(5, dtype=int) # hyperparameter tunning 

In [ ]:
np.zeros((2,2), dtype=int)

In [24]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [25]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [26]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [30]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [33]:
n

(6, 7)

In [34]:
n1

(6, 8)

In [35]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [38]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
n

(6, 7)

In [40]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [41]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [43]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.three(2,3)

In [ ]:
np.ones(2)

In [44]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.

In [47]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [ ]:
range(5)

In [48]:
r = range(5)
r

range(0, 5)

In [49]:
for i in r:
    print(i)

0
1
2
3
4


In [50]:
list(range(5))

[0, 1, 2, 3, 4]

In [51]:
range(1,10)

range(1, 10)

In [52]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
list(range(1,10,3))

[1, 4, 7]

In [54]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [55]:
rand(3,2)

NameError: name 'rand' is not defined

In [56]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [57]:
np.random.rand(5)

array([0.35807987, 0.62023449, 0.10260001, 0.72932222, 0.92100014])

In [58]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.rand(2,4)

In [59]:
np.random.randint(2,4)

2

In [60]:
np.random.randint(2,20) # 2nd argument is exlusive 

10

In [61]:
np.random.randint(0,1) 

0

In [62]:
np.random.randint(10,20,5)

array([10, 12, 14, 12, 14], dtype=int32)

In [63]:
np.random.randint(1,6,4)

array([5, 1, 5, 1], dtype=int32)

In [64]:
np.random.rand(3)

array([0.86429283, 0.61036474, 0.01277053])

In [65]:
np.random.randint(1)  

0

In [66]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [67]:
np.random.randint(-30,20,10) 

array([ 13, -21, -25,  -8, -26, -12,  -5, -13,  -2, -11], dtype=int32)

In [68]:
np.random.randint(20,30,10) 

array([20, 21, 23, 28, 28, 28, 21, 25, 20, 23], dtype=int32)

In [69]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

5

In [70]:
np.random.randint(10,21,3)

array([18, 16, 16], dtype=int32)

In [71]:
np.random.randint(1,12,10)

array([ 1,  8,  9, 10,  1, 11,  9,  6,  7,  1], dtype=int32)

In [72]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[27, 13, 19, 38, 34, 13, 21, 26, 29, 10],
       [37, 35, 29, 13, 14, 15, 26, 19, 18, 39],
       [32, 25, 36, 27, 18, 23, 38, 29, 24, 22],
       [24, 13, 18, 27, 22, 15, 39, 26, 30, 28],
       [16, 12, 18, 32, 14, 22, 32, 38, 20, 36],
       [14, 32, 12, 25, 16, 15, 20, 34, 14, 26],
       [25, 32, 34, 27, 36, 11, 16, 32, 17, 13],
       [24, 37, 24, 27, 35, 15, 29, 11, 13, 27],
       [32, 13, 17, 37, 14, 21, 29, 17, 24, 18],
       [31, 11, 37, 38, 29, 13, 35, 37, 16, 22]], dtype=int32)

In [73]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[61, 55, 65, 77, 27, 51, 52, 18, 69,  7, 69, 54],
       [27, 47, 69,  3, 43, 16,  2, 91, 86, 89, 99, 85],
       [96,  6, 48, 44, 70, 15, 71, 97, 76,  5,  3, 79],
       [42,  2, 28, 89, 44, 24, 43, 98, 90, 19,  7, 86],
       [73, 17, 70, 34, 67,  5, 89, 68, 61, 28, 49,  6],
       [94, 41, 89, 94,  8, 94, 43, 74, 83, 85, 67, 60],
       [84, 71, 70, 77, 80, 85, 12,  7, 60, 47, 57, 88],
       [86, 64, 20, 14, 45, 55, 73, 67, 54, 98, 55, 92],
       [94, 72, 70, 90, 41, 67, 82, 14, 85, 46, 20,  7],
       [39, 64, 75, 28, 30, 87, 47, 41, 58, 11, 40,  2],
       [43, 45, 50, 35, 75,  6, 71, 55, 63, 16, 67, 69],
       [88, 60, 25, 83, 54, 93, 65, 68, 97, 54, 49, 70]], dtype=int32)

In [74]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [76]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [77]:
type(b)

numpy.ndarray

In [78]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [79]:
b[:] 

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [80]:
b[1:3]

array([[12, 13, 19, 10],
       [10, 13, 14, 13]], dtype=int32)

In [81]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [82]:
b[1,2]

np.int32(19)

In [83]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [84]:
b[1,3]

np.int32(10)

In [85]:
b[1,-1]

np.int32(10)

In [86]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [87]:
b[2:3]

array([[10, 13, 14, 13]], dtype=int32)

In [88]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [89]:
b[0:-2] 

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13]], dtype=int32)

In [90]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [91]:
b[0,2] 

np.int32(14)

In [92]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [93]:
b[-5,-3] 

np.int32(16)

In [94]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [95]:
b[-4,2] 

np.int32(19)

In [96]:
np.random.randint(10,20,(4,4))

array([[13, 17, 10, 12],
       [12, 16, 13, 16],
       [12, 16, 17, 18],
       [12, 17, 12, 17]], dtype=int32)

In [97]:
b 

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [98]:
b[-4,-2]

np.int32(19)

In [99]:
b

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

In [100]:
b[-4:2] 

array([[12, 13, 19, 10]], dtype=int32)

In [101]:
b[:]

array([[12, 16, 14, 12],
       [12, 13, 19, 10],
       [10, 13, 14, 13],
       [16, 16, 15, 11],
       [19, 13, 19, 12]], dtype=int32)

## Operations

In [102]:
a = np.random.randint(10,20,10)
a

array([10, 19, 12, 14, 15, 13, 18, 18, 17, 10], dtype=int32)

In [103]:
id(a)

2529212714800

In [104]:
arr

array([0, 1, 2, 3, 4, 5])

In [105]:
arr2 = np.random.randint(0,100,(10,10))

In [106]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [107]:
arr

array([0, 1, 2, 3, 4, 5])

In [108]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [109]:
arr

array([0, 1, 2, 3, 4, 5])

In [110]:
arr[:4] 

array([0, 1, 2, 3])

In [111]:
arr2[:]

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [112]:
arr2[0:5] 

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59]], dtype=int32)

In [113]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [114]:
arr2[1,4] 

np.int32(51)

In [115]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [116]:
arr2[-5,5] 

np.int32(54)

In [117]:
arr2[-5,-5] 

np.int32(54)

In [118]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [119]:
arr2[-5,-5]

np.int32(54)

In [120]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [121]:
arr2[-1,-2]

np.int32(26)

In [122]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [123]:
arr2[::-1]

array([[44, 15, 86, 90, 54,  0, 88, 85, 26, 31],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [74,  4, 49, 91, 48, 46, 12, 33, 14,  3]], dtype=int32)

In [124]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [125]:
arr2[::-2] 

array([[44, 15, 86, 90, 54,  0, 88, 85, 26, 31],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3]], dtype=int32)

In [126]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [127]:
arr2[::-3]

array([[44, 15, 86, 90, 54,  0, 88, 85, 26, 31],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [74,  4, 49, 91, 48, 46, 12, 33, 14,  3]], dtype=int32)

In [128]:
arr2

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35],
       [15, 26, 97, 78,  9, 39, 77, 84, 77, 62],
       [30, 84, 18, 86,  0, 10,  6, 37, 35, 24],
       [44, 15, 86, 90, 54,  0, 88, 85, 26, 31]], dtype=int32)

In [129]:
arr2[:-3] 

array([[74,  4, 49, 91, 48, 46, 12, 33, 14,  3],
       [86, 72, 68, 83, 51, 51, 42, 73, 78,  3],
       [14, 18, 28, 41, 76, 62, 76, 69, 45, 92],
       [97, 49, 45,  6,  3, 35, 45, 98,  6, 76],
       [31, 46, 70, 47, 95, 93, 94, 41, 10, 59],
       [74, 18, 20, 89, 51, 54, 83, 22, 93, 46],
       [46, 54, 68, 81, 58, 56, 41,  0, 16, 35]], dtype=int32)

In [130]:
arr

array([0, 1, 2, 3, 4, 5])

In [131]:
arr.max() 

np.int64(5)

In [132]:
arr.min()

np.int64(0)

In [133]:
arr

array([0, 1, 2, 3, 4, 5])

In [134]:
arr.mean()

np.float64(2.5)

In [135]:
arr

array([0, 1, 2, 3, 4, 5])

In [136]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [137]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import* can you please find the median, mode)

In [138]:
arr

array([0, 1, 2, 3, 4, 5])

In [139]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [140]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [141]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [142]:
arr

array([0, 1, 2, 3, 4, 5])

In [143]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
arr

In [144]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [145]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [146]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [147]:
arr

array([0, 1, 2, 3, 4, 5])

In [148]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [149]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [150]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [151]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [152]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [153]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
arr

In [154]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

## Indexing

In [155]:
mat = np.arange(0,100).reshape(10,10) 

In [156]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [157]:
row = 4
col = 5

In [158]:
col

5

In [159]:
row

4

In [160]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
mat[row,col] 

np.int64(45)

In [162]:
mat[4,5] 

np.int64(45)

In [163]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [164]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [165]:
col = 6

In [166]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [168]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [170]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [171]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [172]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [173]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [174]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [175]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [176]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [177]:
row

4

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [180]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [184]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [186]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [187]:
row

4

In [188]:
col

6

In [189]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [190]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
mat[1,4]

np.int64(14)

In [192]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [193]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [194]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [196]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [199]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [202]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [204]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [216]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [218]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [219]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [220]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [222]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [224]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [226]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
mat[0,1]

np.int64(1)

In [228]:
mat[1,6]

np.int64(16)

In [229]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [231]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [234]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [235]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [237]:
mat[3,5]

np.int64(35)

In [238]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat[1:2,2:4] 

array([[12, 13]])

In [240]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
mat[2:3,2:3] 

array([[22]])

In [242]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [244]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [245]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
mat[2:3,4:5]

array([[24]])

## Masking

In [247]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [248]:
id(mat)

2529215809648

In [249]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [250]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [251]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [252]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [253]:
mat[mat==50] 

array([50])

In [254]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [255]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [256]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [257]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [258]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [259]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [260]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [261]:
a4 = mat[mat==50]
a4

array([50])

# python program to generat otp 

In [262]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 2044


In [263]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [264]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [265]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000024CE0FFD380>


In [266]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
